version: "3"

services:
  mysql-container:
    image: nutritioninformation-mysql
    build:
      dockerfile: mysql-dockerfile
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=nutrition_information
    
  application-container: 
    depends_on: 
      - mysql-container
    image: nutritioninformation-app
    ports: 
      - 7075:7075
    build:
      dockerfile: app-dockerfile
    restart: unless-stopped
    links:
      - "mysql-container:localhost"